apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sendmessage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sendmessage-pods
    spec:
      containers:
      - image: gcr.io/airy-cortex-166611/sendmessage:0.4
        name: sendmessage-container
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http-server
        env:
        - name: SENDGRID_KEY
          valueFrom:
           secretKeyRef:
            name: sendgrid-key
            key: sendgridkey



