apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx-pods
    spec:
      containers:
      - image: gcr.io/airy-cortex-166611/nginx:0.9
        name: nginx-container
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
